info:
  app:
    name: transfer-eureka-server
    version: 1.0

server:
  port: 8000
  host: 127.0.0.1

spring:
  application:
    # 应用名称
    name: transfer-eureka-server

  security:
    basic:
      enabled: true
    user:
      name: transfer
      password: password

eureka:
  instance:
    hostname: localhost
    # 实例通过IP进行访问，而不是域名
    prefer-ip-address: false
  client:
    # 是否将自身实例注册到eureka服务端（true），单节点不进行注册
    register-with-eureka: false
    # 是否从Eureka服务端获取注册信息(true)，注册中心不需要
    fetch-registry: false
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${server.host}:${server.port}/eureka
  server:
    # 关闭保护机制，确保注册中心可以将不可用的实例正确删除
    enable-self-preservation: true
    # 清理无效节点间隔时间 默认 60*1000
    eviction-interval-timer-in-ms: 5000

# Eureka Server 在启动的时候会创建一个定时任务，默认每隔一段时间（默认60秒）将当前清单中超时（默认90秒）没有续约的服务剔除出去

# Eureka Server 保护机制
# 服务注册到Eureka Server 之后，会维护一个心跳连接，告诉Eureka Server 自己还活着。Eureka Server 在运行期间，会统计心跳失败的比例在15分钟之类是否低于85%，
# 如果出现低于的情况下（单机调试的时候很容易满足，实际在生产环境上通常是由于网络不稳定导致），Eureka Server 会将当前的实例注册信息保护起来，让这些实例不会过期，尽可能保护这些注册信息。